# Copyright (c) 2018 The WebRTC project authors. All Rights Reserved.
#
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file in the root of the source
# tree. An additional intellectual property rights grant can be found
# in the file PATENTS.  All contributing project authors may
# be found in the AUTHORS file in the root of the source tree.

import("../../../webrtc.gni")

if (rtc_include_tests) {
  rtc_library("video_codecs_api_unittests") {
    testonly = true
    sources = [
      "builtin_video_encoder_factory_unittest.cc",
      "h264_profile_level_id_unittest.cc",
      "sdp_video_format_unittest.cc",
      "video_codec_test_utils.h",
      "video_codec_unittest.cc",
      "video_decoder_software_fallback_wrapper_unittest.cc",
      "video_encoder_factory_unittest.cc",
      "video_encoder_functional_unittest.cc",
      "video_encoder_rate_control_unittest.cc",
      "video_encoder_software_fallback_wrapper_unittest.cc",
    ]

    if (rtc_use_h265) {
      sources += [ "h265_profile_tier_level_unittest.cc" ]
    }

    deps = [
      ":video_decoder_factory_template_tests",
      ":video_encoder_factory_template_tests",
      "..:builtin_video_decoder_factory",
      "..:builtin_video_encoder_factory",
      "..:libaom_av1_encoder_factory",
      "..:rtc_software_fallback_wrappers",
      "..:scalability_mode",
      "..:video_codecs_api",
      "..:video_decoder_factory_template",
      "..:video_decoder_factory_template_dav1d_adapter",
      "..:video_decoder_factory_template_libvpx_vp8_adapter",
      "..:video_decoder_factory_template_libvpx_vp9_adapter",
      "..:video_decoder_factory_template_open_h264_adapter",
      "..:video_encoder_builders_for_test",
      "..:video_encoder_factory_interface",
      "..:video_encoder_interface",
      "..:video_encoding_general",
      "../..:fec_controller_api",
      "../..:field_trials",
      "../..:frame_generator_api",
      "../..:media_stream_interface",
      "../..:mock_video_encoder",
      "../..:rtp_parameters",
      "../..:scoped_refptr",
      "../../:create_frame_generator",
      "../../../api/units:data_rate",
      "../../../api/units:data_size",
      "../../../api/units:time_delta",
      "../../../api/units:timestamp",
      "../../../common_video",
      "../../../media:media_constants",
      "../../../modules/video_coding:video_codec_interface",
      "../../../modules/video_coding:video_coding_utility",
      "../../../modules/video_coding:webrtc_vp8",
      "../../../rtc_base:checks",
      "../../../rtc_base:logging",
      "../../../rtc_base:platform_thread_types",
      "../../../rtc_base:rtc_event",
      "../../../rtc_base:rtc_numerics",
      "../../../test:create_test_environment",
      "../../../test:create_test_field_trials",
      "../../../test:fake_video_codecs",
      "../../../test:fileutils",
      "../../../test:frame_utils",
      "../../../test:qp_parser_for_test",
      "../../../test:test_support",
      "../../../test:video_test_common",
      "../../../test:video_test_support",
      "../../environment",
      "../../video:encoded_image",
      "../../video:resolution",
      "../../video:video_bitrate_allocator",
      "../../video:video_frame",
      "../../video:video_frame_i010",
      "../../video:video_frame_type",
      "../../video:video_rtp_headers",
      "//testing/gtest",
      "//third_party/abseil-cpp/absl/algorithm:container",
      "//third_party/abseil-cpp/absl/container:inlined_vector",
      "//third_party/abseil-cpp/absl/strings",
      "//third_party/abseil-cpp/absl/strings:string_view",
      "//third_party/libyuv",
    ]
  }

  rtc_library("video_encoder_factory_template_tests") {
    testonly = true
    sources = [ "video_encoder_factory_template_tests.cc" ]

    deps = [
      "..:scalability_mode",
      "..:video_codecs_api",
      "..:video_encoder_factory_template",
      "..:video_encoder_factory_template_libaom_av1_adapter",
      "..:video_encoder_factory_template_libvpx_vp8_adapter",
      "..:video_encoder_factory_template_libvpx_vp9_adapter",
      "..:video_encoder_factory_template_open_h264_adapter",
      "../..:mock_video_encoder",
      "../../../test:create_test_environment",
      "../../../test:test_support",
      "../../environment",
      "//testing/gtest",
    ]
  }

  rtc_library("video_decoder_factory_template_tests") {
    testonly = true
    sources = [ "video_decoder_factory_template_tests.cc" ]

    deps = [
      "..:video_codecs_api",
      "..:video_decoder_factory_template",
      "..:video_decoder_factory_template_dav1d_adapter",
      "..:video_decoder_factory_template_libvpx_vp8_adapter",
      "..:video_decoder_factory_template_libvpx_vp9_adapter",
      "..:video_decoder_factory_template_open_h264_adapter",
      "../..:mock_video_decoder",
      "../../../test:create_test_environment",
      "../../../test:test_support",
      "../../environment",
      "//testing/gtest",
    ]
  }
}
