# Copyright (c) 2018 The WebRTC project authors. All Rights Reserved.
#
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file in the root of the source
# tree. An additional intellectual property rights grant can be found
# in the file PATENTS.  All contributing project authors may
# be found in the AUTHORS file in the root of the source tree.

import("../../webrtc.gni")
if (is_android) {
  import("//build/config/android/config.gni")
  import("//build/config/android/rules.gni")
}

rtc_library("aligned_malloc") {
  sources = [
    "aligned_malloc.cc",
    "aligned_malloc.h",
  ]
  deps = [ "..:checks" ]
}

# Test only utility.
rtc_library("fifo_buffer") {
  testonly = true
  visibility = [
    ":fifo_buffer_unittest",
    "..:rtc_base_tests_utils",
  ]
  sources = [
    "fifo_buffer.cc",
    "fifo_buffer.h",
  ]
  deps = [
    "..:checks",
    "..:macromagic",
    "..:stream",
    "../../api:sequence_checker",
    "../../api/task_queue",
    "../../api/task_queue:pending_task_safety_flag",
  ]
}

rtc_source_set("less_unique_ptr") {
  sources = [ "less_unique_ptr.h" ]
}

if (rtc_include_tests) {
  rtc_cc_test("aligned_malloc_unittest") {
    sources = [ "aligned_malloc_unittest.cc" ]
    deps = [
      ":aligned_malloc",
      "../../test:test_support",
    ]
  }

  rtc_cc_test("always_valid_pointer_unittest") {
    sources = [ "always_valid_pointer_unittest.cc" ]
    deps = [
      ":always_valid_pointer",
      "../../test:test_support",
    ]
  }

  rtc_cc_test("fifo_buffer_unittest") {
    sources = [ "fifo_buffer_unittest.cc" ]
    deps = [
      ":fifo_buffer",
      "..:stream",
      "../../test:run_loop",
      "../../test:test_support",
    ]
  }
}

rtc_source_set("always_valid_pointer") {
  sources = [ "always_valid_pointer.h" ]
  deps = [ "..:checks" ]
}
